apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: create-pod-ns
  namespace: default
rules:
  - apiGroups: [""] 
    resources: ["pods"]
    verbs: ["create", "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: get-secrets-everywhere
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
