apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rbac-role-dubov
subjects:
  - kind: User
    name: dubov  
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role  
  name: create-pod-ns
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rbac-clusterrole-dubov
subjects:
  - kind: User
    name: dubov
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: get-secrets-everywhere
  apiGroup: rbac.authorization.k8s.io
