apiVersion: v1
kind: Pod
metadata:
  name: priv-pod
  namespace: default
  labels:
spec:
  hostNetwork: true
  hostPID: true
  hostIPC: true
  containers:
  - name: priv-pod
    image: ubuntu
    securityContext:
      privileged: true
      capabilities:
       add: ["all"]
    volumeMounts:
    - mountPath: /node-host
      name: hostroot
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
  volumes:
  - name: hostroot
    hostPath:
      path: /
